services:
  nextjs:
    build: .
    ports:
      - "3001:3000"
    extra_hosts:
      - "turnstile-admin.turniket.am:host-gateway"
      - "www.turnstile-admin.turniket.am:host-gateway"
    environment:
      - NEXT_PUBLIC_API_KEY=rJdTPwnZ2G6la28rsspSN2oeoAGIiFqz7Q74yHKyE0GRb31ResNzulaRPv55